project_name: logs-query-exec
builds:
  - dir: .
    binary: logs-query-exec
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - dir: ./cmd/logs-query-exec-request
    binary: logs-query-exec-request
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
