project_name: logs-query-exec
builds:
  - dir: .
    id: logs-query-exec
    binary: logs-query-exec
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - dir: ./cmd/logs-query-exec-request
    id: logs-query-exec-request
    binary: logs-query-exec-request
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: logs-query-exec
    builds:
      - logs-query-exec
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  - id: logs-query-exec-request
    builds:
      - logs-query-exec-request
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
