project_name: logs-query-exec
builds:
  - binary: "logs-query-exec_{{ .Target }}"
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
